#!/bin/sh
set -eu

# Copyright (C) 2013     Volker Grabsch <v@njh.eu>
# Copyright (C) 2015,16  Martin Krafft <madduck@madduck.net>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# Check interface
case "$IFACE" in
    usb0|wwan0|wwx*|wwp*)
        # Okay, go ahead
        ;;
    *)
        # Other network device, nothing to do
        exit 0
        ;;
esac

RETRY_TIMEOUT=3
. /etc/wwan-helper/config

if [ -z "${USBID:-}" ]; then
  USBID=$(lsusb | sed -rne 's,.*ID (0bdb:19(11|3e)) Ericsson Business Mobile Networks BV,\1,p')
fi

SCRIPT="/etc/wwan-helper/usbids/${USBID}"
if [ -r "$SCRIPT" ] && [ -f "$SCRIPT" ] || [ -L "$SCRIPT" ]; then
  . ${SCRIPT}
  exit 0
else
  echo "wwan-helper: Unsupported WWAN device: ${USBID:-(no USB ID provided)}"
  exit 1
fi
