#!/bin/sh
set -eu

# Copyright (C) 2013     Volker Grabsch <v@njh.eu>
# Copyright (C) 2015,16  Martin Krafft <madduck@madduck.net>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

setup() {
  SERIAL_DEV=/dev/ttyACM1
  CHAT_TIMEOUT=2

  # Check ENFORCE_UMTS
  if [ "${IF_WWAN_ENFORCE_UMTS:-no}" = "no" ]; then
      verbose "Not enforcing UMTS, allowing for GSM"
      AT_CFUN_START=1
  elif [ "$IF_WWAN_ENFORCE_UMTS" = "yes" ]; then
      verbose "Enforcing UMTS, not allowing for GSM"
      AT_CFUN_START=6
  else
      fail "Invalid config value for ENFORCE_UMTS"
  fi

  RETRY_TIMEOUT=${IF_WWAN_RETRY_TIMEOUT:-3}
}

init() {
  ip link set "$IFACE" down
}

unlock() {
  modemchat -U "$PIN" TIMEOUT 2 \
    '*EMRDY: 1' \
    'AT+CPIN?' '+CPIN: READY-AT+CPIN="\U"-' \
    '\c' 'OK'
}

register() {
  modemchat -T "$APN" TIMEOUT 2 \
    '*EMRDY: 1' \
    'AT+CFUN='"$AT_CFUN_START" 'OK' \
    'AT+CGDCONT=1,"IP","\T"' 'OK' \
    'AT*ENAP?' '*ENAP:1,""-AT*ENAP=1,1-' \
    '\c' 'OK'
}

connect() {
  ip link set "$IFACE" up
  sleep "$RETRY_TIMEOUT"
  dmesg | grep "cdc_ncm[: ].* $IFACE: network" | tail -1 | grep ' connected$'
}

reset() {
  rmmod cdc_acm
  modprobe cdc_acm
  init
  [ -z "$PIN" ] || unlock
}

disconnect() {
  modemchat TIMEOUT 2 \
    '*EMRDY: 1' \
    'AT*ENAP?' '*ENAP:0,""-AT*ENAP=0-' \
    '\c' 'OK'
}

shutdown() {
  modemchat TIMEOUT 2 \
    '*EMRDY: 1' \
    'AT+CFUN=4' 'OK'
}
